// <auto-generated />
using System;
using LoterySystemBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoterySystemBackend.Migrations
{
    [DbContext(typeof(LotteryDbContext))]
    [Migration("20240318161049_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoterySystemBackend.Models.Draw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DrawDatetime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdateDatetime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WinnerTicketNo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Draw");
                });

            modelBuilder.Entity("LoterySystemBackend.Models.Lottery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Discarded")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssueDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TicketNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lottery");
                });
#pragma warning restore 612, 618
        }
    }
}
